module IrcCommand where

data IrcCommand = CmdOper
                | CmdLusers
                | CmdMotd
                | CmdInvite
                | CmdService
                | CmdDie
                | CmdError
                | CmdNotice
                | CmdPart
                | CmdKill
                | CmdUser
                | CmdPong
                | CmdWhois
                | CmdUsers
                | CmdUserhost
                | CmdAway
                | CmdWho
                | CmdSummon
                | CmdNames
                | CmdWhowas
                | CmdSquit
                | CmdConnect
                | CmdRehash
                | CmdStats
                | CmdAdmin
                | CmdIson
                | CmdVersion
                | CmdPrivmsg
                | CmdPass
                | CmdServlist
                | CmdPing
                | CmdInfo
                | CmdQuit
                | CmdSquery
                | CmdJoin
                | CmdTrace
                | CmdLinks
                | CmdWallops
                | CmdMode
                | CmdList
                | CmdTopic
                | CmdNick
                | CmdRestart
                | CmdTime
                | CmdKick
                | RplStatscommands
                | RplWhoischanop
                | RplServlistend
                | RplTime
                | RplServlist
                | RplYoureservice
                | RplMyinfo
                | RplAway
                | RplTracereconnect
                | RplStatsdline
                | RplList
                | RplGlobalusers
                | RplEndofservices
                | RplEndofinvitelist
                | RplTryagain
                | RplTopic
                | RplUmodeis
                | RplEndofmotd
                | RplUsers
                | RplTraceservice
                | RplBanlist
                | RplUserhost
                | RplEndofusers
                | RplEndofbanlist
                | RplListstart
                | RplTraceend
                | RplEndofwhois
                | RplEndofinfo
                | RplYoureoper
                | RplLuserclient
                | RplChannelmodeis
                | RplAdminme
                | RplIson
                | RplLinks
                | RplEndofwhowas
                | RplNotopic
                | RplChannel
                | RplTracehandshake
                | RplWhowasuser
                | RplTracenewtype
                | RplTraceserver
                | RplStatslinkinfo
                | RplInviting
                | RplMotd
                | RplUniqopis
                | RplLuserunknown
                | RplStatssline
                | RplAdminloc1
                | RplNowaway
                | RplInfostart
                | RplEndofnames
                | RplBounce
                | RplClosing
                | RplWhoreply
                | RplStatsyline
                | RplStatsbline
                | RplWhoisoperator
                | RplWhoisserver
                | RplEndofstats
                | RplExceptlist
                | RplAdminloc2
                | RplEndofexceptlist
                | RplTraceunknown
                | RplEndofwho
                | RplService
                | RplTraceclass
                | RplSummoning
                | RplAdminemail
                | RplWhoisidle
                | RplInvitelist
                | RplTraceconnecting
                | RplEndoflinks
                | RplUsersstart
                | RplInfo
                | RplWhoischannels
                | RplWhoisuser
                | RplMotdstart
                | RplNamreply
                | RplStatsoline
                | RplYourhost
                | RplTracelink
                | RplTopicwhotime
                | RplWelcome
                | RplVersion
                | RplStatskline
                | RplTraceuser
                | RplNousers
                | RplStatsuptime
                | RplListend
                | RplCreated
                | RplLuserchannels
                | RplLocalusers
                | RplUnaway
                | RplRehashing
                | RplLuserop
                | RplMyportis
                | RplTracelog
                | RplStatslline
                | RplLuserme
                | RplStatsnline
                | RplTraceoperator
                | ErrNopermforhost
                | ErrPasswdmismatch
                | ErrNosuchservice
                | ErrBadchannelkey
                | ErrUnknownmode
                | ErrUniqopprivsneeded
                | ErrNickcollision
                | ErrBadmask
                | ErrUseronchannel
                | ErrWasnosuchnick
                | ErrNosuchserver
                | ErrUnavailresource
                | ErrNicknameinuse
                | ErrBadchanmask
                | ErrNeedmoreparams
                | ErrToomanytargets
                | ErrNonicknamegiven
                | ErrKeyset
                | ErrBanlistfull
                | ErrAlreadyregistred
                | ErrNosuchnick
                | ErrChannelisfull
                | ErrChanoprivsneeded
                | ErrRestricted
                | ErrCantkillserver
                | ErrToomanychannels
                | ErrNorecipient
                | ErrNologin
                | ErrNoprivileges
                | ErrYourebannedcreep
                | ErrCannotsendtochan
                | ErrUnknowncommand
                | ErrWildtoplevel
                | ErrNomotd
                | ErrNooperhost
                | ErrYouwillbebanned
                | ErrFileerror
                | ErrInviteonlychan
                | ErrNoorigin
                | ErrNosuchchannel
                | ErrNoadmininfo
                | ErrNotregistered
                | ErrNochanmodes
                | ErrNotoplevel
                | ErrBannedfromchan
                | ErrNotonchannel
                | ErrNotexttosend
                | ErrSummondisabled
                | ErrUsersdontmatch
                | ErrNoservicehost
                | ErrUsersdisabled
                | ErrErroneusnickname
                | ErrUmodeunknownflag
                | ErrUsernotinchannel
                  deriving (Show)
